webpack/tapable

lib/Tapable.js

While profiling our Webpack build I noticed roughly 11% of execution time comes from `Array.prototype.filter`'s call to `defineProperty`, almost all of that filtering comes from `applyPluginsParallelBailResult1`. Calling MDN's `filter` polyfill instead removes that overhead.
Results:
without change:
```303108ms
real	5m5.751s
user	5m4.721s
sys	0m4.788s
```
calling `fastFilter`:
```280671ms
real	4m43.964s
user	4m42.328s
sys	0m4.669s
```

Use a pre-ES5 version of Array filtering to avoid expensive defineProperty call

---

README.md

I noticed this while writing a webpack plugin, `tap` can't return a modification, `register` can, so that's the correct method to show.

Use correct method in docs

---

README.md

To help with https://github.com/webpack/webpack.js.org/issues/2289, adding a short description + example of using context.

Add context usage docs to README

---

lib/HookCodeFactory.js
lib/__tests__/HookTester.js
lib/__tests__/__snapshots__/AsyncSeriesHooks.js.snap
lib/__tests__/__snapshots__/HookCodeFactory.js.snap

Had a problem with a callback not returning a Promise, this made it easier to debug.
Not sure if instead the callback should instead always be wrapped in a Promise so that it doesn't matter…
I had to update the snapshot beforehand, it was wrong on master apparently.

Make Promise hooks easier to debug

---

.prettierrc.js
lib/AsyncParallelBailHook.js
lib/AsyncParallelHook.js
lib/AsyncSeriesBailHook.js
lib/AsyncSeriesHook.js
lib/AsyncSeriesLoopHook.js
lib/AsyncSeriesWaterfallHook.js
lib/Hook.js
lib/HookCodeFactory.js
lib/HookMap.js
lib/MultiHook.js
lib/SyncBailHook.js
lib/SyncWaterfallHook.js
lib/Tapable.js
lib/__tests__/AsyncParallelHooks.js
lib/__tests__/AsyncSeriesHooks.js
lib/__tests__/Hook.js
lib/__tests__/HookCodeFactory.js
lib/__tests__/HookTester.js
lib/__tests__/MultiHook.js
lib/__tests__/SyncBailHook.js
lib/__tests__/SyncHook.js
lib/__tests__/SyncHooks.js
lib/__tests__/Tapable.js
package.json
yarn.lock

Hello. This PR adds [PrettierJS](https://prettier.io), formats all the codebase using [this config](https://github.com/webpack/webpack/blob/master/.prettierrc.js), and adds a corresponding command to npm scripts.
Thank you for checking this out. I hope you'll find it useful.

Add Prettier.js to format code

---

LICENSE

The MIT requires full license text to be present
backport of https://github.com/webpack/tapable/pull/70 to the `tapable-0.2` branch to fix the `webpack 3.x`.

Add LICENSE file (tapable-0.2)

---

lib/HookMap.js
lib/__tests__/Tapable.js

In order to simplify the typings and to clean this package, I propose to remove these redundant methods in the next major version. Meanwhile, they are marked as deprecated.

Deprecate HookMap.tap methods

---

lib/Hook.js

`context` makes `tap` hard to type and is not required at all since the same result could be achieved in user-land.

Deprecate context option

---

.editorconfig
.prettierrc.js
package.json
tapable.d.ts

`MultiHook` is a mess but it's fine for now.
⚠️ These typings are different from the DefinitelyTyped:
```ts
// DefinitelyTyped
SyncBailHook<number, string>
// new typings
SyncBailHook<[number, string]>
```
Hooks are defined as:
```ts
Hook<[foo, bar, baz], qux>
//    ^^^  ^^^  ^^^   ^^^
//     3 arguments     |
//                     |
//     call(a: foo, b: bar, c: baz): qux
//     callAsync(a: foo, b: bar, c: baz, (err: Error, result: qux) => void): void
//     promise(a: foo, b: bar, c: baz): Promise<qux>

Add typings

---

package.json

Exclude tests/snapshots from being included in the distributed npm package, reduces unpacked package size from 233.5 kB to 40.7 kB (~82% reduction). Every little helps!

Exclude tests from being bundled into npm package

---

README.md

the previous example didn't indicate differences between simple hooks and waterfall hooks inside example, which is somehow misleading

update README for returned value clarification

---

lib/AsyncParallelBailHook.js
lib/AsyncParallelHook.js
lib/AsyncSeriesBailHook.js
lib/AsyncSeriesHook.js
lib/AsyncSeriesLoopHook.js
lib/AsyncSeriesWaterfallHook.js
lib/Hook.js
lib/SyncBailHook.js
lib/SyncHook.js
lib/SyncLoopHook.js
lib/SyncWaterfallHook.js
tapable.d.ts

add `name` argument to hook, since enhanced-resolve needs it

refactor hooks to reduce number of hidden maps in methods

---

README.md

When I read the source code, I find the `tap tapAsync tapPromise` API for HookMap is deprecated, but the README still uses these APIs.

fix the HookMap part of the README

---

lib/AsyncSeriesBailHook.js

The code after onResult execution already contains semicolons.

style: Remove semicolon

---

lib/Hook.js
lib/__tests__/Hook.js

I think `name` of `" "` should throw too.

trim name option

---

lib/AsyncParallelBailHook.js
lib/HookCodeFactory.js
lib/__tests__/__snapshots__/HookCodeFactory.js.snap
lib/util-browser.js
package.json

* allow to use tapable in browser
* avoid arrow functions in favor of normal functions
* flag function in good path for eager parsing
fixes #125
fixes #150

add browser support

---

tapable.d.ts

Current behavior:
withOptions return type
- does contain callAsync, which doesn't exist
- doesn't contain tapAsync or tapPromise, which does exist
Expected behavior:
withOptions return type
- should be limited to return value in source
- should include properties depends on the current child instance
related withOptions source code: https://github.com/webpack/tapable/blob/413fa785018406464963c29d172e06d2df42f22e/lib/Hook.js#L105

fix: set withOptions return type to include correct properties

---

tapable.d.ts

Add taps type to hook class, make the following code works
```
const appliedPluginNames: Set<string> = new Set<string>(pluginHook.taps.map(x => x.name));
```
which also fixes https://github.com/webpack/tapable/issues/152

add taps type to hook class

---

README.md

A sync hook can only be tapped with synchronous functions. So if the HookMap want to  use `tapAsync` or `tapPromise` methods, it should use async hooks,  such as `AsyncSeriesHook`.

fix HookMap description

---

README.md
lib/HookCodeFactory.js
lib/__tests__/HookTester.js
lib/__tests__/__snapshots__/AsyncParallelHooks.js.snap
lib/__tests__/__snapshots__/AsyncSeriesHooks.js.snap
lib/__tests__/__snapshots__/HookCodeFactory.js.snap
package.json

fixes https://github.com/webpack/tapable/issues/176
fixes https://github.com/webpack/tapable/pull/177

ci: async hook catch an error when reject a falsy value
